name: Run Python Script

on:
  push:  # triggers on any push to any branch
    branches:
      - '**'

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # or your preferred version

     

      - name: Run Python script
        run: python say_hello.py
